--------------------------------------------------------------------------------


REPLACE VIEW PROD_NBR_VW.NB_REPL_XTRA_XCH_INFO_VW
AS LOCKING ROW FOR ACCESS 
(
SELECT	REPL_REF_NR, REPL_REF_PLAN_CD, CNTR_SEQ_NR, REPL_XTRA_XCH_FR_DT,
		XREF_CNTRCT_NR, REPL_XTRA_XCH_TO_DT, REF_INFO_DATA_FR_DT, CYCL_DT,
		EXPTD_AMT, RECVD_AMT, XREF_COMP_NM, XTRA_XCH_ANALYST_ID, XTRA_XCH_ANALYS_NAME,
		DIST_CHNL_NM, ACTV_DESCR, PLN_ACTV_DT, ACTL_ACTV_DT, ACTV_DT,
		ACTV_ANLS_ID, ACTV_ANLS_NM, STUS_DESC, STUS_EFF_DT, OWN_SSN,
		OWN_NM, SERV_AGT_ID, SERV_AGY_NR, SERV_AGT_NM, SERV_AGT_SSN,
		SERV_AGT_CTY, SERV_AGT_ST, SRC_SYS_ID, RUN_ID, UPDT_RUN_ID, TRANS_DT,
		SRC_DEL_IND
FROM	PROD_NBR.NB_REPL_XTRA_XCH_INFO
);