REPLACE VIEW PROD_NBR_VW.NB_RPT_VW
AS LOCKING ROW FOR ACCESS 
(
SELECT	
		APPL_ID, HLDG_KEY, BEN_AMT, AGMT_TOT_ANNUAL_PREM_AMT, GRADED_PREMIUM_POLICY,
		PREPAID_PREMIUM_IND, CNTR_JURISDICTION, AGENCY_SRC_SYS_PRTY_ID,
		MRG_AGENCY_SRC_SYS_PRTY_ID, MASTERS_GROUP_PARTICIPANT, SOLICITING_AGT_SCARAB_ID,
		SOLICITING_AGT_SRC_SYS_PRTY_ID, SOLICITING_AGT_FULL_NM, SOLICITING_AGT_GOVT_ID,
		SOLICITING_AGT_TYP_CD, GROUP_SRC_SYS_PRTY_ID, GROUP_SRC_SYS_PRTY_ID_5,
		GROUP_FULL_NM, ORGANIZATION_BUSINESS_TYPE_CD, UW_TYPE, BINGO_IND,
		BINGO_REVIEW_DATE, APPLICATION_TYPE_CD, REPLACEMENT_INSURANCE_IND,
		REPLACEMENT_TYPE, PROD_ID, PRODUCT_TYPE, INS_LAST_NAME, INS_FIRST_NAME,
		OCCUPATION_CLASS, OCCUPATION_TYP_CD, INS_GNDR_CD, INS_BRTH_DT,
		INS_AGE, INS_GOVT_ID, INS_ELEC_AD_TXT, UNDERWRITER_CLASS_CD,
		RATED_IND, EXCLUSION_IND, UW_SRC_SYS_PRTY_ID, UW_FULL_NM, UW_TEAM_NM,
		SPECIALIST_SRC_SYS_PRTY_ID, SPECIALIST_FULL_NM, SUBMISSION_DATE,
		CARRIER_INPUT_DATE, CARRIER_SRC_SYS_PRTY_ID, CARRIER_FULL_NM,
		INIT_REVIEW_STRT_STUS_EVENT_DT, INIT_REVIEW_CMPL_STUS_EVENT_DT,
		INITIAL_REVIEW_SRC_SYS_PRTY_ID, INITIAL_REVIEWER_FULL_NM, ISSUE_DATE,
		ISSUED_BY_SRC_SYS_PRTY_ID, ISSUED_BY_FULL_NM, POSTPONE_STATUS_EVENT_DATE,
		POSTPONE_BY_SRC_SYS_PRTY_ID, POSTPONED_BY_FULL_NM, DECLINED_STATUS_EVENT_DATE,
		DECLINED_BY_SRC_SYS_PRTY_ID, DECLINED_BY_FULL_NM, NOT_TAKEN_STATUS_EVENT_DATE,
		NOT_TAKEN_BY_SRC_SYS_PRTY_ID, NOT_TAKEN_BY_FULL_NM, WITHDRAWN_STATUS_EVENT_DATE,
		WITHDRAWN_BY_SRC_SYS_PRTY_ID, WITHDRAWN_FULL_NM, FRST_FINL_ACTION_STUS_EVENT_DT,
		FRST_FINAL_ACTION_DETAIL, FRST_FN_ACT_BY_SRC_SYS_PRTY_ID, FRST_FINAL_ACTION_FULL_NM,
		APPL_INCMP_EVENT_DT, APPL_INCMP_BY_SRC_SYS_PRTY_ID, APPL_INCMP_BY_FULL_NM,
		CURR_STATUS_EVENT_DT, CURR_STATUS_EVENT_DETAIL, CUR_STS_EVN_BY_SRC_SYS_PRTY_ID,
		CURR_STUS_EVENT_BY_FULL_NM, CASE_STATUS_EVENT_DETAIL, CASE_STATUS_EVENT_DATE,
		MAX_TRANS_DT, ESTIMATED_FYC, CM_BINGO_IND, UW_BINGO_IND, CM_BINGO_RVW_DT,
		UW_BINGO_RVW_DT, RPT_PLCM_STUS, RPT_INV_STUS, BUSS_TYP, ISS_RPT_DT,
		WEIGHTED_ANNUAL_PREM_AMT, ANNL_PREM, COV_ADL_PREM, APPL_1035_AS_PREM,
		REPL_TYP_DESC, SALES_UNIT_MANAGER, SRC_PROD_ID, SRC_APPLICATION_TYPE_CD,
		SRC_SYS, EZAPP_IND, SIGN_METH, SALES_MANAGER_UID, SIGNED_DT,APS_IND, BLUE_CHIP,INITIAL_PREM_DT
FROM	PROD_NBR.NB_RPT
);