REPLACE VIEW PROD_NBR_VW.NB_REQ_VW ( APPL_ID,CAS_REQ_ID,REQ_FR_DT,REQ_TO_DT,APPL_DATA_FR_DT,SRC_REQ_ID,REQ_CD,REQ_COLL_METH,REQ_CTG,REQ_CMNT,SRC_REQ_STUS_CD,REQ_STUS_CD,REQ_ORDR_DT,SRC_WRKBNCH_COLL_ID,WRKBNCH_COLL_METH,PHY_NM,SRC_SYS_ID,RUN_ID,UPDT_RUN_ID,TRANS_DT,SRC_DEL_IND,REQ_STUS_DT,SRC_REQ_CTG )
AS LOCKING ROW ACCESS
SELECT PROD_NBR.NB_REQ.APPL_ID,PROD_NBR.NB_REQ.CAS_REQ_ID,PROD_NBR.NB_REQ.REQ_FR_DT,PROD_NBR.NB_REQ.REQ_TO_DT,
PROD_NBR.NB_REQ.APPL_DATA_FR_DT,PROD_NBR.NB_REQ.SRC_REQ_ID,PROD_NBR.NB_REQ.REQ_CD,
PROD_NBR.NB_REQ.REQ_COLL_METH,PROD_NBR.NB_REQ.REQ_CTG,PROD_NBR.NB_REQ.REQ_CMNT,
PROD_NBR.NB_REQ.SRC_REQ_STUS_CD,PROD_NBR.NB_REQ.REQ_STUS_CD,PROD_NBR.NB_REQ.REQ_ORDR_DT,
PROD_NBR.NB_REQ.SRC_WRKBNCH_COLL_ID,PROD_NBR.NB_REQ.WRKBNCH_COLL_METH,PROD_NBR.NB_REQ.PHY_NM,
PROD_NBR.NB_REQ.SRC_SYS_ID,PROD_NBR.NB_REQ.RUN_ID,PROD_NBR.NB_REQ.UPDT_RUN_ID,PROD_NBR.NB_REQ.TRANS_DT,
PROD_NBR.NB_REQ.SRC_DEL_IND,PROD_NBR.NB_REQ.REQ_STUS_DT,PROD_NBR.NB_REQ.SRC_REQ_CTG
FROM PROD_NBR.NB_REQ;