REPLACE VIEW PROD_USIG_CMN_VW.REQ_CD_VW ( REQ_CD,REQ_CD_SHRT_DESC,REQ_CD_DESC ) AS 
	LOCKING ROW
	ACCESS
	SELECT PROD_USIG_CMN.REQ_CD.REQ_CD,PROD_USIG_CMN.REQ_CD.REQ_CD_SHRT_DESC,PROD_USIG_CMN.REQ_CD.REQ_CD_DESC
		FROM PROD_USIG_CMN.REQ_CD;